---
hero_image: images/memory.png
listed: true
copyedit: false
title: Пам'ять
description: В цьому проекті ми створимо гру пам’яті, де вам треба буде запам’ятати і повторити послідовність випадкових кольорів!
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Вступ
  - 
    title: Створіть послідовність кольорів
  - 
    title: Add sound
  - 
    title: Repeat the sequence
  - 
    title: Багаторівнева гра
  - 
    title: Рекорд
  - 
    title: "Завдання: вдоскональте свою гру"
  - 
    title: What next?

