---
hero_image: images/memory.png
listed: true
copyedit: false
title: Geheugenspel
description: Maak een geheugenspel waarin je een reeks willekeurige kleuren onthoudt en herhaalt
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat je nodig hebt
  - 
    title: Maak een kleurenreeks
  - 
    title: 'Uitdaging: een geluid toevoegen'
  - 
    title: Herhaal de reeks
  - 
    title: Meerdere levels
  - 
    title: "Topscore"
  - 
    title: 'Uitdaging: meer blokken maken'

