hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Memory
description: Create a memory game, where you have to memorise and repeat a sequence
  of random colours
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: What you will need
- title: Random colours
- title: 'Challenge: adding sound'
- title: Repeating the sequence
- title: Multiple levels
- title: High score
- title: 'Challenge: Making more blocks'
- title: 'Challenge: Another costume'
- title: 'Challenge: Difficulty level'
