hero_image: images/memory.png
listed: true
copyedit: false
title: Memory
description: Create a memory game in which you memorise and repeat a random sequence of random colours
version: 4.1.0
last_tested: 2018-10-04
steps: 
- title: Introduction
- title: Create a colour sequence
- title: 'Challenge: adding sound'
- title: Repeating the sequence
- title: Multiple levels
- title: High score
- title: 'Challenge: making more blocks'
- title: 'Challenge: another costume'
- title: 'Challenge: difficulty level'
