---
hero_image: images/memory.png
listed: true
copyedit: false
title: メモリ
description: ランダムなカラーシーケンスを記憶して繰り返すゲームを作成する
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: はじめに
  - 
    title: カラーシーケンスを作成する
  - 
    title: サウンドを追加
  - 
    title: シーケンスを繰り返す
  - 
    title: 複数のレベル
  - 
    title: ハイスコア
  - 
    title: "Challenge: ゲームをより良くする"
  - 
    title: 次は何をしますか？

