---
hero_image: images/memory.png
listed: true
copyedit: false
title: メモリ(記憶ゲーム)
description: ばらばらな色の順序を覚えて、その通りに再現するゲームを作りましょう
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: はじめに
  - 
    title: カラーシーケンス(色の順番)を作成します
  - 
    title: 音を追加します
  - 
    title: シーケンス(順番)を再現します
  - 
    title: 複数のレベル
  - 
    title: ハイスコア
  - 
    title: "チャレンジ: ゲームをより良くする"
  - 
    title: 次は何をしますか？

