---
hero_image: images/memory.png
listed: true
copyedit: false
title: メモリ(記憶ゲーム)
description: ばらばらな色の順序を覚えて、その通りに再現するゲームを作りましょう
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: はじめに
  - 
    title: カラーシーケンス(色の順序)を作成します
  - 
    title: 音を追加します
  - 
    title: シーケンス(順序)を再現します
  - 
    title: Multiple levels
  - 
    title: High score
  - 
    title: "チャレンジ: ゲームをより良くする"
  - 
    title: What next?

