---
hero_image: images/memory.png
listed: true
copyedit: false
title: Ký ức
description: Tạo một trò chơi trong đó bạn ghi nhớ và lặp lại các chuỗi màu ngẫu nhiên
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Giới thiệu
  - 
    title: Tạo một chuỗi màu
  - 
    title: Thêm âm thanh
  - 
    title: Lặp lại trình tự
  - 
    title: Nhiều cấp độ
  - 
    title: Điểm cao
  - 
    title: "Thử thách: cải thiện trò chơi của bạn"
  - 
    title: Bước tiếp theo?

