---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memória
description: Cria um jogo em que memorizas e repites sequências de cores aleatórias
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Introdução
  - 
    title: Cria uma sequência de cores
  - 
    title: Adicionar som
  - 
    title: Repete a sequência
  - 
    title: Múltiplos níveis
  - 
    title: Melhor pontuação
  - 
    title: "Desafio: Melhorar o teu jogo"
  - 
    title: O que se segue?

