---
hero_image: images/memory.png
listed: true
copyedit: false
title: Igra pamćenja
description: U ovom projektu kreirat ćeš igru pamćenja u kojoj ćeš trebati upamtiti i ponoviti niz slučajnih boja.
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Igra pamćenja
  - 
    title: Create a colour sequence
  - 
    title: Add sound
  - 
    title: Repeat the sequence
  - 
    title: Multiple levels
  - 
    title: High score
  - 
    title: "Challenge: improve your game"
  - 
    title: What next?

