hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Memoria
description: ¡Crea un juego de memoria en el que tengas que memorizar y repetir una secuencia de colores aleatorios!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Colores al azar
- title: 'Reto: Añadir sonido'
- title: Repite la secuencia
- title: Niveles múltiples
- title: Puntuación más alta
- title: 'Reto: Crear más bloques'
- title: 'Reto: Otro disfraz'
- title: 'Reto: Nivel de dificultad'
