---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memoria
description: '¡Crea un juego de memoria en el que tengas que memorizar y repetir una secuencia de colores aleatorios!'
version: 4.1.0
last_tested: 2018-10-04
steps:
  - title: Introducción
  - title: Crea una secuencia de colores
  - title: Añade sonido
  - title: Repite la secuencia
  - title: Varios niveles
  - title: Mejor resultado
  - title: "Desafío: mejora tu juego"
  - title: '¿Qué viene a continuación?'

