---
hero_image: images/memory.png
listed: true
copyedit: false
title: Cofio
description: Creu gêm gofio, lle mae'n rhaid i ti gofio ac ailadrodd dilyniant o liwiau ar hap
version: 4
last_tested: 2017-01-01
steps:
  - title: Cyflwyniad
  - title: Creu dilyniant o liwiau
  - title: Ychwanegu sain
  - title: Ailadrodd y dilyniant
  - title: Lefelau gwahanol
  - title: Sgôr Uchel
  - title: "Her: gwella dy gêm"
  - title: Beth nesaf?

