hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Cofio
description: Creu gêm gofio, lle mae'n rhaid i ti gofio ac ailadrodd dilyniant o liwiau ar hap!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Cyflwyniad
- title: Lliwiau ar hap
- title: 'Her: Ychwanegu sain'
- title: Ailadrodd y dilyniant
- title: Lefelau gwahanol
- title: Sgôr Uchel
- title: 'Her: Creu mwy o flociau'
- title: 'Her: Gwisg arall'
- title: 'Her: Lefelau y gêm'
