---
hero_image: images/memory.png
listed: true
copyedit: false
title: Gedächtnis
description: Erstelle ein Spiel, in dem du zufällige Farbsequenzen auswendig lernst
  und wiederholst
version: 4.1.0
last_tested: 2018-10-04
steps:
- title: Einleitung
- title: Erstelle ein zufällige Farbenfolge
- title: Geräusche hinzufügen
  completion:
  - engaged
- title: Wiederhole die Reihenfolge
- title: Mehrere Ebenen
- title: Highscore
  completion:
  - internal
- title: 'Herausforderung: Verbessere dein Spiel'