---
hero_image: images/memory.png
listed: true
copyedit: false
title: Gedächtnis
description: In diesem Projekt erstellst Du ein Gedächtnis-Spiel, bei dem man sich eine Folge von zufälligen Farben merken und wiederholen muss!
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Zufällige Farben
  - 
    title: 'Herausforderung: Geräusche hinzufügen'
  - 
    title: Reihenfolge wiederholen
  - 
    title: Mehrere Ebenen
  - 
    title: Höchstpunktestand
  - 
    title: "Herausforderung: Erstelle mehr Blöcke"
  - 
    title: 'Herausforderung: Ein weiteres Kostüm'

