---
hero_image: images/memory.png
listed: true
copyedit: false
title: Gedächtnis
description: In diesem Projekt erstellst Du ein Gedächtnis-Spiel, bei dem man sich eine Reihe von zufälligen Farben merken und wiederholen muss
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Einleitung
  - 
    title: 'Herausforderung: Geräusche hinzufügen'
  - 
    title: 'Herausforderung: Geräusche hinzufügen'
  - 
    title: Reihenfolge wiederholen
  - 
    title: Mehrfachstimmen
  - 
    title: Hohe Punktzahl
  - 
    title: "Herausforderung: Verbessere dein Spiel"
  - 
    title: Wie geht es weiter?

