---
hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Memorie
description: În acest proiect vei crea un joc de memorie unde va trebui să memorezi și să repeți o secvență aleatorie de culori!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Memory
  - 
    title: Ce ai nevoie
  - 
    title: Creează o secvenţă de culori
  - 
    title: 'Provocare: Adaugă sunet'
  - 
    title: Repetă secvența
  - 
    title: Nivele multiple
  - 
    title: Cel mai mare scor
  - 
    title: 'Provocare: Creează mai multe blocuri'
  - 
    title: 'Provocare: Un nou costum'
  - 
    title: 'Provocare: Nivel de dificultate'
