---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memorie
description: În acest proiect vei crea un joc de memorie unde va trebui să memorezi și să repeți o secvență aleatorie de culori!
version: 4.2.1
last_tested: 2018-10-04
steps:
  - 
    title: Memory
  - 
    title: Creează o secvenţă de culori
  - 
    title: Adăugați un sunet
  - 
    title: Repetați secvența
  - 
    title: Nivele multiple
  - 
    title: Cel mai mare scor
  - 
    title: "Provocare: îmbunătățiți jocul"
  - 
    title: Ce urmează?

