---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memorie
description: În acest proiect vei crea un joc de memorie unde va trebui să memorezi și să repeți o secvență aleatorie de culori!
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Memory
  - 
    title: Create a colour sequence
  - 
    title: Add sound
  - 
    title: Repeat the sequence
  - 
    title: Multiple levels
  - 
    title: High score
  - 
    title: "Challenge: improve your game"
  - 
    title: What next?

