---
hero_image: images/memory.png
listed: true
copyedit: false
title: Jogo da memória
description: Crie um jogo de memória no qual você memoriza e repete uma sequência
  aleatória de cores
version: 4.1.0
last_tested: 2018-10-04
steps:
- title: Introdução
- title: Crie uma sequência de cores
- title: Adicione um som
  completion:
  - engaged
- title: Repita a sequência
- title: Múltiplos níveis
- title: Recorde
  completion:
  - internal
- title: 'Desafio: melhore seu jogo'
- title: E agora?
