hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Jogo da Memória
description: Neste projeto, você criará um jogo de memória onde você tem que memorizar e repetir uma sequência de cores aleatórias!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2017-01-01
steps: 
- title: Jogo da Memória