---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memoria
description: Create a game in which you memorise and repeat random colour sequences
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Introduction
  - 
    title: Crear una secuencia de colores
  - 
    title: Añadir sonido
  - 
    title: Repetir la secuencia
  - 
    title: Múltiples niveles
  - 
    title: Puntuación mayor
  - 
    title: "Desafío: mejora tu juego"
  - 
    title: '¿Qué sigue?'

