---
hero_image: images/memory.png
listed: true
copyedit: false
title: الذاكرة
description: أنشئ لعبة ذاكرة تتذكر فيها تسلسلًا عشوائيًا من الألوان وتكرِّره
version: 4.1.0
last_tested: 2018-10-04
steps:
- title: المقدمة
  completion: engaged
- title: إنشاء تسلسل لوني
- title: إضافة صوت
- title: كرر التسلسل
- title: مستويات متعددة
- title: درجة عالية
  completion: internal
- title: 'التحدي: تحسين لعبتك'
- title: ما التالي؟
