---
hero_image: images/memory.png
listed: true
copyedit: false
title: Test na pamięć
description: Utwórz grę, w której zapamiętujesz i powtarzasz losowe sekwencje kolorów
version: 4.1.0
last_tested: 2018-10-04
steps:
  - title: Wprowadzenie
  - title: Utwórz sekwencję kolorów
  - title: Dodaj dźwięk
  - title: Powtórz sekwencję
  - title: Kolejne poziomy
  - title: Najlepszy wynik
  - title: "Wyzwanie: udoskonal swoją grę"
  - title: Co dalej?

