---
hero_image: images/memory.png
listed: true
copyedit: false
title: Test na pamięć
description: Naucz się, jak stworzyć własną grę pamięciową.
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Wprowadzenie
  - 
    title: Utwórz sekwencję kolorów
  - 
    title: Dodaj dźwięk
  - 
    title: Powtórz sekwencję
  - 
    title: Multiple levels
  - 
    title: Tabela wyników
  - 
    title: "Wyzwanie: udoskonal swoją grę"
  - 
    title: Co następne?

