---
hero_image: images/memory.png
listed: true
copyedit: false
title: Igra pamćenja
description: Create a game in which you memorise and repeat random colour sequences
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Uvod
  - 
    title: Create a colour sequence
  - 
    title: Add sound
  - 
    title: Repeat the sequence
  - 
    title: Multiple levels
  - 
    title: High score
  - 
    title: "Challenge: improve your game"
  - 
    title: What next?

