---
hero_image: images/memory.png
listed: true
copyedit: false
title: Igra pamćenja
description: Kreiraj igru pamćenja u kojoj treba da zapamtiš i ponoviš slučajan niz boja
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Uvod
  - 
    title: Napravi niz boja
  - 
    title: Napravi niz boja
  - 
    title: 'Izazov: dodavanje zvuka'
  - 
    title: Više nivoa
  - 
    title: Najbolji rezultat
  - 
    title: "Izazov: poboljšaj svoju igru"
  - 
    title: 'Izazov: više olovaka'

