---
hero_image: images/memory.png
listed: true
copyedit: false
title: Mémoire
description: Crées un jeu de mémoire où tu devras mémoriser et répéter une séquence aléatoire de couleurs!
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Des couleurs aléatoires
  - 
    title: 'Défi : Ajouter du son'
  - 
    title: Répéter la séquence
  - 
    title: De multiples niveaux
  - 
    title: Meilleur pointage
  - 
    title: "Défi : Créer d'autres blocs"
  - 
    title: 'Défi : Un autre costume'

