---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memoria
description: Crea un gioco di memoria, dove devi memorizzare e ripetere una sequenza di colori a caso!
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: Introduzione
  - 
    title: Crea una sequenza di colori
  - 
    title: 'Sfida: Aggiungi un suono'
  - 
    title: Ripetere la sequenza
  - 
    title: Livelli multipli
  - 
    title: Punteggio alto
  - 
    title: "Sfida: migliora il tuo gioco"
  - 
    title: 'Sfida: Più matite'

