hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Memoria
description: Crea un gioco di memoria, dove devi memorizzare e ripetere una sequenza di colori a caso!
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: ''
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduzione
- title: Colori a caso
- title: 'Sfida: Aggiungi un suono'
- title: Ripetere la sequenza
- title: Livelli multipli
- title: Punteggio alto
- title: 'Sfida: Crea altri blocchi'
- title: 'Sfida: Un altro costume'
- title: 'Sfida: Livello difficoltà'
