---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memoria
description: Crea un gioco di memoria, dove devi memorizzare e ripetere una sequenza
  di colori casuali
version: 4.1.0
last_tested: 2018-10-04
steps:
- title: Introduzione
- title: Crea una sequenza di colori
- title: Aggiungi un suono
  completion:
  - engaged
- title: Ripetere la sequenza
- title: Livelli multipli
- title: Record
  completion:
  - internal
- title: 'Sfida: migliora il tuo gioco'