---
hero_image: images/memory.png
listed: true
copyedit: false
title: Memoria
description: Crea un gioco di memoria, dove devi memorizzare e ripetere una sequenza di colori a caso!
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Colori a caso
  - 
    title: 'Sfida: Aggiungi un suono'
  - 
    title: Ripetere la sequenza
  - 
    title: Livelli multipli
  - 
    title: Punteggio alto
  - 
    title: "Sfida: Crea altri blocchi"
  - 
    title: 'Sfida: Un altro costume'

