---
hero_image: images/memory.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Memoria
description: Crea un gioco di memoria dove devi memorizzare e ripetere una sequenza di colori a caso
original_url: https://codeclubprojects.org/en-GB/scratch/memory
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4.0.1
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Crea una sequenza di colori
  - 
    title: 'Sfida: Aggiungere un suono'
  - 
    title: Ripetere la sequenza
  - 
    title: Livelli multipli
  - 
    title: Record
  - 
    title: 'Sfida: Crea altri blocchi'
  - 
    title: 'Sfida: Un altro costume'
  - 
    title: 'Sfida: Livello di difficoltà'
