---
hero_image: images / memory.png
listed: true
copyedit: false
title: මතකය(Memory)
description: නැවත නැවත දිස්වෙන අහඹු(random) වර්ණ(colour) අනුපිළිවෙලවල්(sequences) මතක තබාගෙන කරන ක්‍රීඩාවක් සෑදීම
version: 4.1.0
last_tested: 2018-10-04
steps:
  - 
    title: හැදින්වීම
  - 
    title: වර්ණ(colour) අනුක්‍රමයක්(sequence එකක්) සෑදීම
  - 
    title: ශබ්ද එක් කිරීම
  - 
    title: අනුක්‍රමය නැවත(repeat) ක්‍රියාත්මක කිරීම
  - 
    title: බහු(multiple) මට්ටම්(levels)
  - 
    title: වැඩිම(high) ලකුණු(score)
  - 
    title: "අභියෝගය: ඔබේ ක්‍රීඩාව වැඩි දියුණු කිරීම"
  - 
    title: ඊලඟට කුමක්ද?

